### ISSUE TITLE
version="v2.0" not recognized

### ISSUE THREAD

**Issue by misbahsy** [LambdaLabsML/lambda-diffusers#16]
Please see the error below:

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 239, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/v2.0/model_index.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 326, in load_config
    config_file = hf_hub_download(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1067, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1376, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 249, in hf_raise_for_status
    raise RevisionNotFoundError(message, response) from e
huggingface_hub.utils._errors.RevisionNotFoundError: 404 Client Error. (Request ID: Root=1-6390d17e-0e0fc74b06ef2e36080f654f)

Revision Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/v2.0/model_index.json.
Invalid rev id: v2.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/diff-lambdalabs-img-variations/download.py", line 18, in <module>
    download_model()
  File "/home/ubuntu/diff-lambdalabs-img-variations/download.py", line 13, in download_model
    model = StableDiffusionImageVariationPipeline.from_pretrained(repo_id, revision="v2.0", use_auth_token=HF_AUTH_TOKEN)
  File "/opt/conda/lib/python3.9/site-packages/diffusers/pipeline_utils.py", line 454, in from_pretrained
    config_dict = cls.load_config(
  File "/opt/conda/lib/python3.9/site-packages/diffusers/configuration_utils.py", line 348, in load_config
    raise EnvironmentError(
OSError: v2.0 is not a valid git identifier (branch name, tag name or commit id) that exists for this model name. Check the model page at 'https://huggingface.co/lambdalabs/sd-image-variations-diffusers' for available revisions.

**Comment by Hritikbansal** [comment]
@justinpinkney facing the same problem

**Comment by averad** [comment]
To correct the issue you need to: 
1. Go to the model's hugging face page. 
- https://huggingface.co/lambdalabs/sd-image-variations-diffusers/
2. Click on "Files and Versions" 
![1](https://user-images.githubusercontent.com/640619/206927815-0ff1c7f2-ba4e-4006-8bf0-613be65f993d.png)

3. Click on "main" to see the drop down of available "revisions"
![2](https://user-images.githubusercontent.com/640619/206927973-4385250b-a8dc-4ade-afc2-aa83530ddca9.png)

v2.0 is not a listed "revision" for that model, I believe you would want to pull/download the "main" revision

Corrected Script Example:
```
from diffusers import StableDiffusionImageVariationPipeline
from PIL import Image

device = "cuda:0"
sd_pipe = StableDiffusionImageVariationPipeline.from_pretrained(
  "lambdalabs/sd-image-variations-diffusers",
  revision="main",
  )
```

----------------------------------------------

I've opened a discussion on the models page asking the creator update the model to include v2.0 as a valid branch or to update the example code.

https://huggingface.co/lambdalabs/sd-image-variations-diffusers/discussions/6

**Comment by Hritikbansal** [comment]
That makes sense! Btw which model gets loaded if you don't specify revision argument at all?

**Comment by averad** [comment]
The main repo

**Comment by justinpinkney** [comment]
this is fixed now
