### ISSUE TITLE
How to do torchscript inference for unet

### ISSUE THREAD

**Issue by yuananf** [LambdaLabsML/lambda-diffusers#9]
I followed the instruction here and successfully exported the jitted unet. But failed to use it with inference. https://huggingface.co/lambdalabs/sd-image-variations-diffusers

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [2], in <cell line: 3>()
      2 num_samples = 1
      3 with torch.inference_mode():
----> 4     image = pipe(num_samples*[im], guidance_scale=3.0, num_inference_steps=50)
      5     image = image["sample"][0]
      7 image

File ~/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/stable-diffusion/lambda-diffusers/lambda_diffusers/pipelines/pipeline_stable_diffusion_im_embed.py:137, in StableDiffusionImageEmbedPipeline.__call__(self, input_image, height, width, num_inference_steps, guidance_scale, eta, generator, latents, output_type, **kwargs)
    134     latent_model_input = latent_model_input / ((sigma**2 + 1) ** 0.5)
    136 # predict the noise residual
--> 137 noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=image_embeddings)["sample"]
    139 # perform guidance
    140 if do_classifier_free_guidance:

File ~/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

Input In [1], in TracedUNet.forward(self, latent_model_input, t, encoder_hidden_states)
     27 def forward(self, latent_model_input, t, encoder_hidden_states):
---> 28     sample = unet_traced(latent_model_input, t, encoder_hidden_states)[0]
     29     return UNet2DConditionOutput(sample=sample)

File ~/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/diffusers/models/unet_2d_condition.py", line 44, in forward
    _4 = ops.prim.NumToTensor(torch.size(sample, 0))
    timesteps = torch.expand(timestep, [int(_4)])
    input0 = torch.to((time_proj).forward(timesteps, ), 6)
                       ~~~~~~~~~~~~~~~~~~ <--- HERE
    _5 = (time_embedding).forward(input0, )
    _6 = (conv_in).forward(sample, )
  File "code/__torch__/diffusers/models/embeddings.py", line 15, in forward
    _2 = torch.to(torch.unsqueeze(_1, 1), 6)
    _3 = torch.slice(torch.unsqueeze(emb, 0), 1, 0, 9223372036854775807)
    emb0 = torch.mul(_2, _3)
           ~~~~~~~~~ <--- HERE
    emb1 = torch.mul(emb0, CONSTANTS.c2)
    emb2 = torch.cat([torch.sin(emb1), torch.cos(emb1)], -1)

Traceback of TorchScript, original code (most recent call last):
/home/ubuntu/stable-diffusion/diffusers/src/diffusers/models/embeddings.py(46): get_timestep_embedding
/home/ubuntu/stable-diffusion/diffusers/src/diffusers/models/embeddings.py(92): forward
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
/home/ubuntu/stable-diffusion/diffusers/src/diffusers/models/unet_2d_condition.py(268): forward
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py(1118): _slow_forward
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py(1130): _call_impl
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/jit/_trace.py(967): trace_module
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/jit/_trace.py(750): trace
/tmp/ipykernel_5411/692496257.py(38): <cell line: 38>
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/IPython/core/interactiveshell.py(3398): run_code
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/IPython/core/interactiveshell.py(3338): run_ast_nodes
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/IPython/core/interactiveshell.py(3135): run_cell_async
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/IPython/core/async_helpers.py(129): _pseudo_sync_runner
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/IPython/core/interactiveshell.py(2936): _run_cell
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/IPython/core/interactiveshell.py(2881): run_cell
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/zmqshell.py(528): run_cell
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/ipkernel.py(383): do_execute
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/kernelbase.py(730): execute_request
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/kernelbase.py(406): dispatch_shell
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/kernelbase.py(499): process_one
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/kernelbase.py(510): dispatch_queue
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/asyncio/events.py(81): _run
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/asyncio/base_events.py(1859): _run_once
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/asyncio/base_events.py(570): run_forever
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/tornado/platform/asyncio.py(215): start
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/kernelapp.py(712): start
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/traitlets/config/application.py(976): launch_instance
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/site-packages/ipykernel/__main__.py(4): <module>
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/runpy.py(87): _run_code
/home/ubuntu/anaconda3/envs/ldm/lib/python3.8/runpy.py(194): _run_module_as_main
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by justinpinkney** [comment]
hmmm, something is on the wrong device. I think this might be a 'device pinning' problem from jit. If something gets made on the device during jit (e.g. maybe the null condition of zeros) it is always stuck on that device afterwards. You can see some workaround in this post I think: https://paulbridger.com/posts/mastering-torchscript/
